// Offline airport database — instant autocomplete, no API needed
// Format: [IATA, CityName, AirportName, CountryCode]
const RAW = [
  // ── Thailand ──
  ["BKK","Bangkok","Suvarnabhumi Airport","TH"],
  ["DMK","Bangkok","Don Mueang Airport","TH"],
  ["CNX","Chiang Mai","Chiang Mai Airport","TH"],
  ["HKT","Phuket","Phuket Airport","TH"],
  ["USM","Koh Samui","Koh Samui Airport","TH"],
  ["UTH","Udon Thani","Udon Thani Airport","TH"],
  ["URT","Surat Thani","Surat Thani Airport","TH"],
  ["KBV","Krabi","Krabi Airport","TH"],
  ["HDY","Hat Yai","Hat Yai Airport","TH"],
  ["CEI","Chiang Rai","Chiang Rai Airport","TH"],
  ["NAW","Narathiwat","Narathiwat Airport","TH"],
  ["NST","Nakhon Si Thammarat","Nakhon Si Thammarat Airport","TH"],
  ["PHS","Phitsanulok","Phitsanulok Airport","TH"],
  ["TDX","Trat","Trat Airport","TH"],
  // ── India ──
  ["DEL","Delhi","Indira Gandhi Int'l Airport","IN"],
  ["BOM","Mumbai","Chhatrapati Shivaji Airport","IN"],
  ["BLR","Bengaluru","Kempegowda Airport","IN"],
  ["MAA","Chennai","Chennai Airport","IN"],
  ["HYD","Hyderabad","Rajiv Gandhi Airport","IN"],
  ["CCU","Kolkata","Netaji Subhas Chandra Bose Airport","IN"],
  ["AMD","Ahmedabad","Sardar Vallabhbhai Patel Airport","IN"],
  ["PNQ","Pune","Pune Airport","IN"],
  ["GOI","Goa","Goa Airport","IN"],
  ["COK","Kochi","Cochin Airport","IN"],
  ["JAI","Jaipur","Jaipur Airport","IN"],
  ["LKO","Lucknow","Chaudhary Charan Singh Airport","IN"],
  ["SXR","Srinagar","Srinagar Airport","IN"],
  ["IXC","Chandigarh","Chandigarh Airport","IN"],
  ["GAU","Guwahati","Lokpriya Gopinath Bordoloi Airport","IN"],
  ["IXB","Bagdogra","Bagdogra Airport","IN"],
  ["TRV","Thiruvananthapuram","Trivandrum Airport","IN"],
  ["VTZ","Visakhapatnam","Visakhapatnam Airport","IN"],
  ["BHO","Bhopal","Raja Bhoj Airport","IN"],
  ["NAG","Nagpur","Dr. Babasaheb Ambedkar Airport","IN"],
  ["IDR","Indore","Devi Ahilyabai Holkar Airport","IN"],
  ["PAT","Patna","Jay Prakash Narayan Airport","IN"],
  ["ATQ","Amritsar","Sri Guru Ram Dass Jee Airport","IN"],
  ["IXE","Mangaluru","Mangaluru Airport","IN"],
  ["VGA","Vijayawada","Vijayawada Airport","IN"],
  ["STV","Surat","Surat Airport","IN"],
  ["VNS","Varanasi","Lal Bahadur Shastri Airport","IN"],
  ["IXZ","Port Blair","Veer Savarkar Airport","IN"],
  ["IXM","Madurai","Madurai Airport","IN"],
  ["UDR","Udaipur","Maharana Pratap Airport","IN"],
  // ── UAE ──
  ["DXB","Dubai","Dubai International Airport","AE"],
  ["AUH","Abu Dhabi","Abu Dhabi International Airport","AE"],
  ["SHJ","Sharjah","Sharjah International Airport","AE"],
  ["RKT","Ras Al Khaimah","Ras Al Khaimah Airport","AE"],
  ["AAN","Al Ain","Al Ain Airport","AE"],
  // ── Singapore ──
  ["SIN","Singapore","Changi Airport","SG"],
  // ── Malaysia ──
  ["KUL","Kuala Lumpur","Kuala Lumpur Int'l Airport","MY"],
  ["SZB","Kuala Lumpur","Subang Airport","MY"],
  ["PEN","Penang","Penang Airport","MY"],
  ["LGK","Langkawi","Langkawi Airport","MY"],
  ["BKI","Kota Kinabalu","Kota Kinabalu Airport","MY"],
  ["KCH","Kuching","Kuching Airport","MY"],
  ["MYY","Miri","Miri Airport","MY"],
  ["JHB","Johor Bahru","Senai Airport","MY"],
  // ── Indonesia ──
  ["CGK","Jakarta","Soekarno-Hatta Airport","ID"],
  ["DPS","Bali","Ngurah Rai Airport","ID"],
  ["SUB","Surabaya","Juanda Airport","ID"],
  ["MDC","Manado","Sam Ratulangi Airport","ID"],
  ["UPG","Makassar","Sultan Hasanuddin Airport","ID"],
  ["BPN","Balikpapan","Sultan Aji Muhammad Sulaiman Airport","ID"],
  ["PLM","Palembang","Sultan Mahmud Badaruddin II Airport","ID"],
  ["BTH","Batam","Hang Nadim Airport","ID"],
  ["PKU","Pekanbaru","Sultan Syarif Kasim II Airport","ID"],
  ["PNK","Pontianak","Supadio Airport","ID"],
  ["PDG","Padang","Minangkabau Airport","ID"],
  ["MLG","Malang","Abdul Rachman Saleh Airport","ID"],
  ["YIA","Yogyakarta","Yogyakarta Airport","ID"],
  ["SOC","Solo","Adi Soemarmo Airport","ID"],
  ["LOP","Lombok","Lombok International Airport","ID"],
  ["AMQ","Ambon","Pattimura Airport","ID"],
  ["TIM","Timika","Moses Kilangin Airport","ID"],
  ["KOE","Kupang","El Tari Airport","ID"],
  ["LBI","Makassar","Makassar Airport","ID"],
  // ── Philippines ──
  ["MNL","Manila","Ninoy Aquino Airport","PH"],
  ["CEB","Cebu","Mactan-Cebu Airport","PH"],
  ["DVO","Davao","Francisco Bangoy Airport","PH"],
  ["ILO","Iloilo","Iloilo Airport","PH"],
  ["CYP","Calbayog","Calbayog Airport","PH"],
  ["KLO","Kalibo","Kalibo Airport","PH"],
  ["RXS","Roxas","Roxas Airport","PH"],
  ["BCD","Bacolod","Bacolod-Silay Airport","PH"],
  ["ZAM","Zamboanga","Zamboanga Airport","PH"],
  ["CGY","Cagayan de Oro","Laguindingan Airport","PH"],
  ["PPS","Puerto Princesa","Puerto Princesa Airport","PH"],
  ["TAG","Tagbilaran","Tagbilaran Airport","PH"],
  ["GES","General Santos","General Santos Airport","PH"],
  // ── Japan ──
  ["NRT","Tokyo","Narita Airport","JP"],
  ["HND","Tokyo","Haneda Airport","JP"],
  ["KIX","Osaka","Kansai Airport","JP"],
  ["ITM","Osaka","Itami Airport","JP"],
  ["NGO","Nagoya","Chubu Centrair Airport","JP"],
  ["CTS","Sapporo","New Chitose Airport","JP"],
  ["FUK","Fukuoka","Fukuoka Airport","JP"],
  ["OKA","Okinawa","Naha Airport","JP"],
  ["HIJ","Hiroshima","Hiroshima Airport","JP"],
  ["KMJ","Kumamoto","Kumamoto Airport","JP"],
  ["MYJ","Matsuyama","Matsuyama Airport","JP"],
  ["KOJ","Kagoshima","Kagoshima Airport","JP"],
  ["SDJ","Sendai","Sendai Airport","JP"],
  ["KMQ","Komatsu","Komatsu Airport","JP"],
  // ── South Korea ──
  ["ICN","Seoul","Incheon Airport","KR"],
  ["GMP","Seoul","Gimpo Airport","KR"],
  ["PUS","Busan","Gimhae Airport","KR"],
  ["CJU","Jeju","Jeju Airport","KR"],
  ["TAE","Daegu","Daegu Airport","KR"],
  ["CJJ","Cheongju","Cheongju Airport","KR"],
  // ── China ──
  ["PEK","Beijing","Beijing Capital Airport","CN"],
  ["PKX","Beijing","Daxing Airport","CN"],
  ["PVG","Shanghai","Pudong Airport","CN"],
  ["SHA","Shanghai","Hongqiao Airport","CN"],
  ["CAN","Guangzhou","Baiyun Airport","CN"],
  ["SZX","Shenzhen","Bao'an Airport","CN"],
  ["CTU","Chengdu","Tianfu Airport","CN"],
  ["KMG","Kunming","Changshui Airport","CN"],
  ["XIY","Xi'an","Xianyang Airport","CN"],
  ["WUH","Wuhan","Tianhe Airport","CN"],
  ["CSX","Changsha","Huanghua Airport","CN"],
  ["XMN","Xiamen","Gaoqi Airport","CN"],
  ["FOC","Fuzhou","Changle Airport","CN"],
  ["HGH","Hangzhou","Xiaoshan Airport","CN"],
  ["CGO","Zhengzhou","Xinzheng Airport","CN"],
  ["TSN","Tianjin","Binhai Airport","CN"],
  ["NKG","Nanjing","Lukou Airport","CN"],
  ["HAK","Haikou","Meilan Airport","CN"],
  ["SYX","Sanya","Phoenix Airport","CN"],
  ["URC","Urumqi","Diwopu Airport","CN"],
  ["CGQ","Changchun","Longjia Airport","CN"],
  ["DLC","Dalian","Zhoushuizi Airport","CN"],
  ["SHE","Shenyang","Taoxian Airport","CN"],
  ["TAO","Qingdao","Jiaodong Airport","CN"],
  ["HRB","Harbin","Taiping Airport","CN"],
  ["NNG","Nanning","Wuxu Airport","CN"],
  ["KWE","Guiyang","Longdongbao Airport","CN"],
  ["LHW","Lanzhou","Zhongchuan Airport","CN"],
  ["KWL","Guilin","Liangjiang Airport","CN"],
  // ── Vietnam ──
  ["SGN","Ho Chi Minh City","Tan Son Nhat Airport","VN"],
  ["HAN","Hanoi","Nội Bài Airport","VN"],
  ["DAD","Da Nang","Da Nang Airport","VN"],
  ["CXR","Nha Trang","Cam Ranh Airport","VN"],
  ["PQC","Phu Quoc","Phu Quoc Airport","VN"],
  ["HPH","Hai Phong","Cat Bi Airport","VN"],
  ["HUI","Hue","Phu Bai Airport","VN"],
  ["VCA","Can Tho","Can Tho Airport","VN"],
  ["VDH","Dong Hoi","Dong Hoi Airport","VN"],
  ["UIH","Qui Nhon","Phu Cat Airport","VN"],
  // ── Myanmar ──
  ["RGN","Yangon","Mingaladon Airport","MM"],
  ["MDL","Mandalay","Mandalay Airport","MM"],
  ["NYT","Naypyitaw","Naypyitaw Airport","MM"],
  ["AKY","Sittwe","Sittwe Airport","MM"],
  // ── Cambodia ──
  ["PNH","Phnom Penh","Phnom Penh Airport","KH"],
  ["REP","Siem Reap","Siem Reap Airport","KH"],
  // ── Laos ──
  ["VTE","Vientiane","Wattay Airport","LA"],
  ["LPQ","Luang Prabang","Luang Prabang Airport","LA"],
  // ── Sri Lanka ──
  ["CMB","Colombo","Bandaranaike Airport","LK"],
  ["HRI","Hambantota","Mattala Rajapaksa Airport","LK"],
  // ── Nepal ──
  ["KTM","Kathmandu","Tribhuvan Airport","NP"],
  ["PKR","Pokhara","Pokhara Airport","NP"],
  // ── Bangladesh ──
  ["DAC","Dhaka","Hazrat Shahjalal Airport","BD"],
  ["CGP","Chittagong","Shah Amanat Airport","BD"],
  // ── Pakistan ──
  ["KHI","Karachi","Jinnah Airport","PK"],
  ["LHE","Lahore","Allama Iqbal Airport","PK"],
  ["ISB","Islamabad","Islamabad Airport","PK"],
  ["PEW","Peshawar","Bacha Khan Airport","PK"],
  ["MUX","Multan","Multan Airport","PK"],
  // ── Middle East ──
  ["DOH","Doha","Hamad Airport","QA"],
  ["KWI","Kuwait City","Kuwait Airport","KW"],
  ["BAH","Manama","Bahrain Airport","BH"],
  ["MCT","Muscat","Muscat Airport","OM"],
  ["AMM","Amman","Queen Alia Airport","JO"],
  ["TLV","Tel Aviv","Ben Gurion Airport","IL"],
  ["BEY","Beirut","Rafic Hariri Airport","LB"],
  ["CAI","Cairo","Cairo Airport","EG"],
  ["RUH","Riyadh","King Khalid Airport","SA"],
  ["JED","Jeddah","King Abdulaziz Airport","SA"],
  ["MED","Medina","Prince Mohammad Bin Abdulaziz Airport","SA"],
  ["DMM","Dammam","King Fahd Airport","SA"],
  ["THR","Tehran","Imam Khomeini Airport","IR"],
  ["IKA","Tehran","Imam Khomeini International Airport","IR"],
  ["KBL","Kabul","Kabul Airport","AF"],
  // ── Europe — UK ──
  ["LHR","London","Heathrow Airport","GB"],
  ["LGW","London","Gatwick Airport","GB"],
  ["STN","London","Stansted Airport","GB"],
  ["LTN","London","Luton Airport","GB"],
  ["LCY","London","City Airport","GB"],
  ["MAN","Manchester","Manchester Airport","GB"],
  ["EDI","Edinburgh","Edinburgh Airport","GB"],
  ["GLA","Glasgow","Glasgow Airport","GB"],
  ["BHX","Birmingham","Birmingham Airport","GB"],
  ["BRS","Bristol","Bristol Airport","GB"],
  ["NCL","Newcastle","Newcastle Airport","GB"],
  ["EMA","Nottingham","East Midlands Airport","GB"],
  ["ABZ","Aberdeen","Aberdeen Airport","GB"],
  ["BFS","Belfast","Belfast International Airport","GB"],
  ["LBA","Leeds","Leeds Bradford Airport","GB"],
  ["SOU","Southampton","Southampton Airport","GB"],
  ["EXT","Exeter","Exeter Airport","GB"],
  ["NWI","Norwich","Norwich Airport","GB"],
  // ── Europe — France ──
  ["CDG","Paris","Charles de Gaulle Airport","FR"],
  ["ORY","Paris","Orly Airport","FR"],
  ["NCE","Nice","Nice Airport","FR"],
  ["MRS","Marseille","Provence Airport","FR"],
  ["LYS","Lyon","Saint-Exupéry Airport","FR"],
  ["TLS","Toulouse","Blagnac Airport","FR"],
  ["BOD","Bordeaux","Bordeaux Airport","FR"],
  ["NTE","Nantes","Nantes Airport","FR"],
  ["SXB","Strasbourg","Strasbourg Airport","FR"],
  ["LIL","Lille","Lille Airport","FR"],
  // ── Europe — Germany ──
  ["FRA","Frankfurt","Frankfurt Airport","DE"],
  ["MUC","Munich","Munich Airport","DE"],
  ["BER","Berlin","Brandenburg Airport","DE"],
  ["HAM","Hamburg","Hamburg Airport","DE"],
  ["DUS","Düsseldorf","Düsseldorf Airport","DE"],
  ["CGN","Cologne","Cologne Bonn Airport","DE"],
  ["STR","Stuttgart","Stuttgart Airport","DE"],
  ["NUE","Nuremberg","Nuremberg Airport","DE"],
  ["LEJ","Leipzig","Leipzig Airport","DE"],
  ["HAJ","Hanover","Hannover Airport","DE"],
  ["DTM","Dortmund","Dortmund Airport","DE"],
  ["FKB","Karlsruhe","Karlsruhe Baden-Baden Airport","DE"],
  // ── Europe — Spain ──
  ["MAD","Madrid","Barajas Airport","ES"],
  ["BCN","Barcelona","El Prat Airport","ES"],
  ["AGP","Malaga","Málaga Airport","ES"],
  ["PMI","Palma de Mallorca","Palma Airport","ES"],
  ["ALC","Alicante","Alicante Airport","ES"],
  ["VLC","Valencia","Valencia Airport","ES"],
  ["SVQ","Seville","Seville Airport","ES"],
  ["TFS","Tenerife","Tenerife South Airport","ES"],
  ["LPA","Las Palmas","Gran Canaria Airport","ES"],
  ["IBZ","Ibiza","Ibiza Airport","ES"],
  ["FUE","Fuerteventura","Fuerteventura Airport","ES"],
  ["ACE","Lanzarote","Lanzarote Airport","ES"],
  ["BIO","Bilbao","Bilbao Airport","ES"],
  ["SDR","Santander","Santander Airport","ES"],
  // ── Europe — Italy ──
  ["FCO","Rome","Fiumicino Airport","IT"],
  ["CIA","Rome","Ciampino Airport","IT"],
  ["MXP","Milan","Malpensa Airport","IT"],
  ["LIN","Milan","Linate Airport","IT"],
  ["BGY","Milan","Orio al Serio Airport","IT"],
  ["VCE","Venice","Marco Polo Airport","IT"],
  ["PMO","Palermo","Palermo Airport","IT"],
  ["NAP","Naples","Capodichino Airport","IT"],
  ["BLQ","Bologna","Guglielmo Marconi Airport","IT"],
  ["FLR","Florence","Peretola Airport","IT"],
  ["CTA","Catania","Fontanarossa Airport","IT"],
  ["BRI","Bari","Karol Wojtyła Airport","IT"],
  ["TRN","Turin","Caselle Airport","IT"],
  ["PSA","Pisa","Galileo Galilei Airport","IT"],
  // ── Europe — Netherlands ──
  ["AMS","Amsterdam","Schiphol Airport","NL"],
  ["EIN","Eindhoven","Eindhoven Airport","NL"],
  ["RTM","Rotterdam","Rotterdam The Hague Airport","NL"],
  // ── Europe — Switzerland ──
  ["ZRH","Zurich","Zurich Airport","CH"],
  ["GVA","Geneva","Geneva Airport","CH"],
  ["BSL","Basel","EuroAirport Basel","CH"],
  // ── Europe — Austria ──
  ["VIE","Vienna","Vienna Airport","AT"],
  ["GRZ","Graz","Graz Airport","AT"],
  ["INN","Innsbruck","Innsbruck Airport","AT"],
  // ── Europe — Belgium ──
  ["BRU","Brussels","Brussels Airport","BE"],
  ["CRL","Brussels","Charleroi Airport","BE"],
  ["ANR","Antwerp","Antwerp Airport","BE"],
  // ── Europe — Portugal ──
  ["LIS","Lisbon","Lisbon Airport","PT"],
  ["OPO","Porto","Francisco Sá Carneiro Airport","PT"],
  ["FAO","Faro","Faro Airport","PT"],
  ["FNC","Funchal","Madeira Airport","PT"],
  // ── Europe — Scandinavia ──
  ["CPH","Copenhagen","Kastrup Airport","DK"],
  ["BLL","Billund","Billund Airport","DK"],
  ["ARN","Stockholm","Arlanda Airport","SE"],
  ["GOT","Gothenburg","Landvetter Airport","SE"],
  ["OSL","Oslo","Gardermoen Airport","NO"],
  ["BGO","Bergen","Bergen Airport","NO"],
  ["HEL","Helsinki","Helsinki Airport","FI"],
  ["TMP","Tampere","Tampere-Pirkkala Airport","FI"],
  // ── Europe — Poland ──
  ["WAW","Warsaw","Chopin Airport","PL"],
  ["KRK","Krakow","John Paul II Airport","PL"],
  ["GDN","Gdansk","Lech Walesa Airport","PL"],
  ["WRO","Wroclaw","Wroclaw Airport","PL"],
  ["POZ","Poznan","Poznan Airport","PL"],
  ["KTW","Katowice","Katowice Airport","PL"],
  // ── Europe — Czech Republic ──
  ["PRG","Prague","Václav Havel Airport","CZ"],
  ["BRQ","Brno","Brno Airport","CZ"],
  // ── Europe — Hungary ──
  ["BUD","Budapest","Budapest Airport","HU"],
  // ── Europe — Romania ──
  ["OTP","Bucharest","Henri Coandă Airport","RO"],
  ["CLJ","Cluj-Napoca","Cluj Airport","RO"],
  // ── Europe — Greece ──
  ["ATH","Athens","Eleftherios Venizelos Airport","GR"],
  ["SKG","Thessaloniki","Macedonia Airport","GR"],
  ["HER","Heraklion","Nikos Kazantzakis Airport","GR"],
  ["RHO","Rhodes","Diagoras Airport","GR"],
  ["CFU","Corfu","Ioannis Kapodistrias Airport","GR"],
  ["SMI","Samos","Samos Airport","GR"],
  ["JMK","Mykonos","Mykonos Airport","GR"],
  ["JSI","Skiathos","Skiathos Airport","GR"],
  ["JTR","Santorini","Thira Airport","GR"],
  // ── Europe — Turkey ──
  ["IST","Istanbul","Istanbul Airport","TR"],
  ["SAW","Istanbul","Sabiha Gökçen Airport","TR"],
  ["ADB","Izmir","Adnan Menderes Airport","TR"],
  ["AYT","Antalya","Antalya Airport","TR"],
  ["ESB","Ankara","Esenboğa Airport","TR"],
  ["TZX","Trabzon","Trabzon Airport","TR"],
  ["ERZ","Erzurum","Erzurum Airport","TR"],
  ["DLM","Dalaman","Dalaman Airport","TR"],
  ["BJV","Bodrum","Milas-Bodrum Airport","TR"],
  ["GZP","Alanya","Gazipasa Airport","TR"],
  ["MLX","Malatya","Erhaç Airport","TR"],
  // ── Europe — Russia ──
  ["SVO","Moscow","Sheremetyevo Airport","RU"],
  ["DME","Moscow","Domodedovo Airport","RU"],
  ["VKO","Moscow","Vnukovo Airport","RU"],
  ["LED","St Petersburg","Pulkovo Airport","RU"],
  ["OVB","Novosibirsk","Tolmachevo Airport","RU"],
  ["SVX","Yekaterinburg","Koltsovo Airport","RU"],
  ["AER","Sochi","Sochi Airport","RU"],
  ["KZN","Kazan","Kazan Airport","RU"],
  ["UFA","Ufa","Ufa Airport","RU"],
  ["ROV","Rostov-on-Don","Platov Airport","RU"],
  // ── Europe — Ukraine ──
  ["KBP","Kyiv","Boryspil Airport","UA"],
  ["IEV","Kyiv","Igor Sikorsky Airport","UA"],
  ["LWO","Lviv","Danylo Halytskyi Airport","UA"],
  // ── Europe — Other ──
  ["DUB","Dublin","Dublin Airport","IE"],
  ["ORK","Cork","Cork Airport","IE"],
  ["LUX","Luxembourg","Luxembourg Airport","LU"],
  ["KEF","Reykjavik","Keflavik Airport","IS"],
  ["RVN","Rovaniemi","Rovaniemi Airport","FI"],
  ["TLL","Tallinn","Lennart Meri Airport","EE"],
  ["RIX","Riga","Riga Airport","LV"],
  ["VNO","Vilnius","Vilnius Airport","LT"],
  ["HRK","Kharkiv","Kharkiv Airport","UA"],
  ["ODS","Odessa","Odessa Airport","UA"],
  ["KIV","Chisinau","Chisinau Airport","MD"],
  ["SOF","Sofia","Sofia Airport","BG"],
  ["SKP","Skopje","Skopje Airport","MK"],
  ["TIA","Tirana","Mother Teresa Airport","AL"],
  ["TGD","Podgorica","Podgorica Airport","ME"],
  ["SPU","Split","Split Airport","HR"],
  ["ZAG","Zagreb","Zagreb Airport","HR"],
  ["DBV","Dubrovnik","Dubrovnik Airport","HR"],
  ["BEG","Belgrade","Nikola Tesla Airport","RS"],
  ["TSR","Timisoara","Traian Vuia Airport","RO"],
  ["SBZ","Sibiu","Sibiu Airport","RO"],
  ["LJU","Ljubljana","Jože Pučnik Airport","SI"],
  ["BTS","Bratislava","Bratislava Airport","SK"],
  ["OSR","Ostrava","Leos Janacek Airport","CZ"],
  // ── North America — USA ──
  ["JFK","New York","John F. Kennedy Airport","US"],
  ["LGA","New York","LaGuardia Airport","US"],
  ["EWR","Newark","Newark Airport","US"],
  ["LAX","Los Angeles","Los Angeles Airport","US"],
  ["SFO","San Francisco","San Francisco Airport","US"],
  ["ORD","Chicago","O'Hare Airport","US"],
  ["MDW","Chicago","Midway Airport","US"],
  ["ATL","Atlanta","Hartsfield-Jackson Airport","US"],
  ["DFW","Dallas","Dallas/Fort Worth Airport","US"],
  ["DAL","Dallas","Love Field","US"],
  ["DEN","Denver","Denver Airport","US"],
  ["MIA","Miami","Miami Airport","US"],
  ["FLL","Fort Lauderdale","Fort Lauderdale Airport","US"],
  ["MCO","Orlando","Orlando Airport","US"],
  ["LAS","Las Vegas","Harry Reid Airport","US"],
  ["SEA","Seattle","Seattle-Tacoma Airport","US"],
  ["BOS","Boston","Logan Airport","US"],
  ["PHX","Phoenix","Sky Harbor Airport","US"],
  ["IAH","Houston","George Bush Airport","US"],
  ["HOU","Houston","Hobby Airport","US"],
  ["MSP","Minneapolis","Minneapolis-Saint Paul Airport","US"],
  ["DTW","Detroit","Detroit Metro Airport","US"],
  ["CLT","Charlotte","Douglas Airport","US"],
  ["PHL","Philadelphia","Philadelphia Airport","US"],
  ["BWI","Baltimore","Baltimore-Washington Airport","US"],
  ["IAD","Washington","Dulles Airport","US"],
  ["DCA","Washington","Reagan Airport","US"],
  ["SAN","San Diego","San Diego Airport","US"],
  ["TPA","Tampa","Tampa Airport","US"],
  ["PDX","Portland","Portland Airport","US"],
  ["SLC","Salt Lake City","Salt Lake City Airport","US"],
  ["MSY","New Orleans","Louis Armstrong Airport","US"],
  ["STL","St Louis","Lambert Airport","US"],
  ["BNA","Nashville","Nashville Airport","US"],
  ["AUS","Austin","Austin-Bergstrom Airport","US"],
  ["SAT","San Antonio","San Antonio Airport","US"],
  ["MCI","Kansas City","Kansas City Airport","US"],
  ["RDU","Raleigh","Raleigh-Durham Airport","US"],
  ["IND","Indianapolis","Indianapolis Airport","US"],
  ["CMH","Columbus","John Glenn Columbus Airport","US"],
  ["PIT","Pittsburgh","Pittsburgh Airport","US"],
  ["CLE","Cleveland","Cleveland Hopkins Airport","US"],
  ["MKE","Milwaukee","Mitchell Airport","US"],
  ["JAX","Jacksonville","Jacksonville Airport","US"],
  ["ABQ","Albuquerque","Albuquerque Airport","US"],
  ["OMA","Omaha","Eppley Airfield","US"],
  ["OGG","Maui","Kahului Airport","US"],
  ["HNL","Honolulu","Daniel K. Inouye Airport","US"],
  ["ANC","Anchorage","Ted Stevens Airport","US"],
  ["SJC","San Jose","Mineta Airport","US"],
  ["OAK","Oakland","Oakland Airport","US"],
  ["SMF","Sacramento","Sacramento Airport","US"],
  ["BUR","Burbank","Hollywood Burbank Airport","US"],
  ["LGB","Long Beach","Long Beach Airport","US"],
  ["ONT","Ontario","Ontario Airport","US"],
  // ── Canada ──
  ["YYZ","Toronto","Pearson Airport","CA"],
  ["YVR","Vancouver","Vancouver Airport","CA"],
  ["YUL","Montreal","Trudeau Airport","CA"],
  ["YYC","Calgary","Calgary Airport","CA"],
  ["YEG","Edmonton","Edmonton Airport","CA"],
  ["YOW","Ottawa","Macdonald-Cartier Airport","CA"],
  ["YHZ","Halifax","Stanfield Airport","CA"],
  ["YWG","Winnipeg","James Armstrong Richardson Airport","CA"],
  ["YQR","Regina","Regina Airport","CA"],
  ["YXE","Saskatoon","Diefenbaker Airport","CA"],
  ["YQB","Quebec City","Jean Lesage Airport","CA"],
  // ── Mexico ──
  ["MEX","Mexico City","Benito Juárez Airport","MX"],
  ["CUN","Cancun","Cancun Airport","MX"],
  ["GDL","Guadalajara","Miguel Hidalgo Airport","MX"],
  ["MTY","Monterrey","General Mariano Escobedo Airport","MX"],
  ["SJD","Los Cabos","Los Cabos Airport","MX"],
  ["PVR","Puerto Vallarta","Gustavo Díaz Ordaz Airport","MX"],
  ["MZT","Mazatlan","General Rafael Buelna Airport","MX"],
  ["ZIH","Zihuatanejo","Ixtapa-Zihuatanejo Airport","MX"],
  ["HMO","Hermosillo","Hermosillo Airport","MX"],
  ["TIJ","Tijuana","General Abelardo Airport","MX"],
  // ── South America ──
  ["GRU","São Paulo","Guarulhos Airport","BR"],
  ["CGH","São Paulo","Congonhas Airport","BR"],
  ["GIG","Rio de Janeiro","Galeão Airport","BR"],
  ["SDU","Rio de Janeiro","Santos Dumont Airport","BR"],
  ["BSB","Brasilia","Brasilia Airport","BR"],
  ["SSA","Salvador","Deputado Luis Eduardo Airport","BR"],
  ["FOR","Fortaleza","Pinto Martins Airport","BR"],
  ["REC","Recife","Guararapes Airport","BR"],
  ["MAO","Manaus","Eduardo Gomes Airport","BR"],
  ["BEL","Belém","Val-de-Cans Airport","BR"],
  ["POA","Porto Alegre","Salgado Filho Airport","BR"],
  ["CWB","Curitiba","Afonso Pena Airport","BR"],
  ["FLN","Florianopolis","Hercílio Luz Airport","BR"],
  ["BOG","Bogota","El Dorado Airport","CO"],
  ["MDE","Medellín","José María Córdova Airport","CO"],
  ["CLO","Cali","Alfonso Bonilla Aragón Airport","CO"],
  ["CTG","Cartagena","Rafael Núñez Airport","CO"],
  ["LIM","Lima","Jorge Chávez Airport","PE"],
  ["SCL","Santiago","Arturo Merino Benítez Airport","CL"],
  ["PMC","Puerto Montt","El Tepual Airport","CL"],
  ["EZE","Buenos Aires","Ezeiza Airport","AR"],
  ["AEP","Buenos Aires","Jorge Newbery Airport","AR"],
  ["COR","Córdoba","Taravella Airport","AR"],
  ["GYE","Guayaquil","José Joaquín de Olmedo Airport","EC"],
  ["UIO","Quito","Mariscal Sucre Airport","EC"],
  ["ASU","Asuncion","Silvio Pettirossi Airport","PY"],
  ["MVD","Montevideo","Carrasco Airport","UY"],
  ["VVI","Santa Cruz","Viru-Viru Airport","BO"],
  ["LPB","La Paz","El Alto Airport","BO"],
  ["CCS","Caracas","Simón Bolívar Airport","VE"],
  ["MIA","Miami","Miami Airport","US"],
  ["PTY","Panama City","Tocumen Airport","PA"],
  ["GUA","Guatemala City","La Aurora Airport","GT"],
  ["SAL","San Salvador","Monseñor Óscar Romero Airport","SV"],
  ["SJO","San José","Juan Santamaría Airport","CR"],
  // ── Africa ──
  ["JNB","Johannesburg","O.R.Tambo Airport","ZA"],
  ["CPT","Cape Town","Cape Town Airport","ZA"],
  ["DUR","Durban","King Shaka Airport","ZA"],
  ["NBO","Nairobi","Jomo Kenyatta Airport","KE"],
  ["MBA","Mombasa","Moi Airport","KE"],
  ["ADD","Addis Ababa","Bole Airport","ET"],
  ["DAR","Dar es Salaam","Julius Nyerere Airport","TZ"],
  ["ACC","Accra","Kotoka Airport","GH"],
  ["ABV","Abuja","Nnamdi Azikiwe Airport","NG"],
  ["LOS","Lagos","Murtala Muhammed Airport","NG"],
  ["CMN","Casablanca","Mohammed V Airport","MA"],
  ["RAK","Marrakech","Menara Airport","MA"],
  ["TUN","Tunis","Carthage Airport","TN"],
  ["ALG","Algiers","Houari Boumediene Airport","DZ"],
  ["HRE","Harare","Robert Gabriel Mugabe Airport","ZW"],
  ["LUN","Lusaka","Kenneth Kaunda Airport","ZM"],
  ["MRU","Mauritius","Sir Seewoosagur Ramgoolam Airport","MU"],
  ["ANT","Antananarivo","Ivato Airport","MG"],
  ["TNR","Antananarivo","Ivato Airport","MG"],
  ["ROB","Monrovia","Roberts Airport","LR"],
  ["ABJ","Abidjan","Félix-Houphouët-Boigny Airport","CI"],
  ["DKR","Dakar","Blaise Diagne Airport","SN"],
  ["OUA","Ouagadougou","Thomas Sankara Airport","BF"],
  ["NIM","Niamey","Diori Hamani Airport","NE"],
  // ── Australia & NZ ──
  ["SYD","Sydney","Kingsford Smith Airport","AU"],
  ["MEL","Melbourne","Melbourne Airport","AU"],
  ["BNE","Brisbane","Brisbane Airport","AU"],
  ["PER","Perth","Perth Airport","AU"],
  ["ADL","Adelaide","Adelaide Airport","AU"],
  ["CBR","Canberra","Canberra Airport","AU"],
  ["HBA","Hobart","Hobart Airport","AU"],
  ["CNS","Cairns","Cairns Airport","AU"],
  ["OOL","Gold Coast","Gold Coast Airport","AU"],
  ["TSV","Townsville","Townsville Airport","AU"],
  ["DRW","Darwin","Darwin Airport","AU"],
  ["AKL","Auckland","Auckland Airport","NZ"],
  ["CHC","Christchurch","Christchurch Airport","NZ"],
  ["WLG","Wellington","Wellington Airport","NZ"],
  ["ZQN","Queenstown","Queenstown Airport","NZ"],
  ["DUD","Dunedin","Dunedin Airport","NZ"],
  // ── Maldives / Seychelles / Pacific ──
  ["MLE","Malé","Velana Airport","MV"],
  ["SEZ","Mahé","Seychelles Airport","SC"],
  ["NAN","Nadi","Nadi Airport","FJ"],
  ["PPT","Papeete","Fa'a'ā Airport","PF"],
  ["SUV","Suva","Nausori Airport","FJ"],
  ["BKI","Kota Kinabalu","Kota Kinabalu Airport","MY"],
];

// Build index for fast search
const AIRPORTS = RAW.map(([iataCode, cityName, name, countryCode]) => ({
  iataCode, cityName, name, countryCode, subType: "AIRPORT",
}));

function normalize(s) {
  return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export function searchAirportsLocal(keyword, limit = 10) {
  if (!keyword || keyword.length < 2) return [];
  const kw = normalize(keyword.trim());

  const exact = [], startCity = [], startName = [], containsCity = [], containsName = [];

  for (const ap of AIRPORTS) {
    const city = normalize(ap.cityName);
    const name = normalize(ap.name);
    const iata = ap.iataCode.toLowerCase();

    if (iata === kw) {
      exact.push(ap);
    } else if (city.startsWith(kw)) {
      startCity.push(ap);
    } else if (name.startsWith(kw)) {
      startName.push(ap);
    } else if (city.includes(kw)) {
      containsCity.push(ap);
    } else if (name.includes(kw) || iata.includes(kw)) {
      containsName.push(ap);
    }
  }

  return [...exact, ...startCity, ...startName, ...containsCity, ...containsName].slice(0, limit);
}
